import { useRef } from "react";

import type { ReconnectTrigger } from "../types/useReconnect";

/**
 * Latched description of what the next observed `close` event should
 * commit, generated by the heartbeat path when an active socket exists
 * and we have to wait for the close to actually fire.
 */
export type WebSocketPendingCloseAction = {
  error: Event | null;
  reconnectTrigger: ReconnectTrigger | null;
};

type ControllerState = {
  /**
   * The user explicitly called `close()`. Suppresses auto-reconnect on
   * the next deps-effect run unless cleared by `open()` / `reconnect()`.
   */
  manualClose: boolean;
  /**
   * The user explicitly called `open()` (or `reconnect()`). Forces the
   * deps-effect to connect even when `connect={false}`.
   */
  manualOpen: boolean;
  /**
   * Reconnect is suppressed for the close that is currently in flight.
   * Cleared by the close-handler once it has used the value, or by an
   * incoming `open` event.
   */
  reconnectSuppressed: boolean;
  /**
   * One-shot guard: the very next close should bypass the auto-reconnect
   * decision entirely. Consumed by the close handler.
   */
  skipNextCloseReconnect: boolean;
  /**
   * Latched action that the close handler should commit when the close
   * fires. Set by the heartbeat path with an active socket. Consumed by
   * the close handler.
   */
  pendingCloseAction: WebSocketPendingCloseAction | null;
  /**
   * Sticky terminal error (e.g. parse-error). Survives until cleared by
   * a user action (`open()` / `close()` / `reconnect()`) or replaced by
   * a subsequent heartbeat result. Read by both the close handler and
   * the deps-effect.
   */
  terminalError: Event | null;
};

const createInitialState = (): ControllerState => ({
  manualClose: false,
  manualOpen: false,
  pendingCloseAction: null,
  reconnectSuppressed: false,
  skipNextCloseReconnect: false,
  terminalError: null
});

/**
 * Imperative control-plane state for `useWebSocket`. Consolidates the
 * six interacting mutable booleans/refs that previously lived directly
 * inside the hook into a single object whose transitions are exposed
 * through named methods.
 *
 * Behaviour is intentionally identical to the previous pile of refs;
 * this is a pure refactor that makes the control flow easier to read
 * and review. None of the methods cause renders -- the controller is
 * stored in a single `useRef`, not in React state.
 */
export type WebSocketController = {
  /** Did the user explicitly call `close()` and not `open()` since? */
  hasManualCloseRequested: () => boolean;
  /** Did the user explicitly call `open()` (or `reconnect()`) and not `close()` since? */
  hasManualOpenRequested: () => boolean;
  /** Sticky terminal error, or `null`. Non-destructive read. */
  peekTerminalError: () => Event | null;
  /** Should the close currently in flight skip auto-reconnect? */
  isReconnectSuppressed: () => boolean;

  /** `open()` was called. */
  noteUserOpenRequested: () => void;
  /** `close()` was called, before `closeSocket(trackClose)` runs. */
  noteUserCloseRequested: () => void;
  /** `reconnect()` was called, before the controlled close runs. */
  noteUserReconnectRequested: () => void;
  /** `reconnect()`'s controlled close has finished, before scheduling. */
  noteUserReconnectClosed: () => void;

  /** Socket fired `open`; clear all manual / suppress / terminal flags. */
  noteSocketOpened: () => void;

  /**
   * Heartbeat decided to act, but no active socket is around to close.
   * Sets the terminal error iff the action is not a reconnect.
   */
  noteHeartbeatNoActiveSocket: (input: {
    shouldReconnect: boolean;
    error: Event;
  }) => void;
  /**
   * Heartbeat decided to act and there is an active socket: latch a
   * pending close action and prepare both reconnect guards.
   */
  noteHeartbeatActiveSocketClose: (input: WebSocketPendingCloseAction) => void;

  /** Parser threw; latch a terminal error and prepare both guards. */
  noteParseError: (error: Event) => void;

  /**
   * The deps-effect itself initiated a close because the URL changed,
   * `connect` became false, or the runtime is unsupported. The next
   * close should not auto-reconnect.
   */
  noteEffectInitiatedClose: () => void;

  /** Consume the latched pending action, clearing it. */
  consumePendingCloseAction: () => WebSocketPendingCloseAction | null;
  /** Consume the one-shot skip flag, clearing it. */
  consumeSkipNextCloseReconnect: () => boolean;
  /** Reset the imminent-close suppression after the close has been processed. */
  clearReconnectSuppression: () => void;
};

export const useWebSocketController = (): WebSocketController => {
  const ref = useRef<ControllerState | null>(null);

  if (ref.current === null) {
    ref.current = createInitialState();
  }

  const state = ref.current;

  const controllerRef = useRef<WebSocketController | null>(null);

  if (controllerRef.current === null) {
    controllerRef.current = {
      clearReconnectSuppression: () => {
        state.reconnectSuppressed = false;
      },
      consumePendingCloseAction: () => {
        const action = state.pendingCloseAction;
        state.pendingCloseAction = null;
        return action;
      },
      consumeSkipNextCloseReconnect: () => {
        const skip = state.skipNextCloseReconnect;
        state.skipNextCloseReconnect = false;
        return skip;
      },
      hasManualCloseRequested: () => state.manualClose,
      hasManualOpenRequested: () => state.manualOpen,
      isReconnectSuppressed: () => state.reconnectSuppressed,
      noteEffectInitiatedClose: () => {
        state.reconnectSuppressed = true;
      },
      noteHeartbeatActiveSocketClose: (input) => {
        state.manualOpen = false;
        state.terminalError =
          input.reconnectTrigger === null ? input.error : null;
        state.pendingCloseAction = input;
        state.skipNextCloseReconnect = true;
        state.reconnectSuppressed = true;
      },
      noteHeartbeatNoActiveSocket: ({ shouldReconnect, error }) => {
        state.manualOpen = false;
        state.terminalError = shouldReconnect ? null : error;
      },
      noteParseError: (error) => {
        state.terminalError = error;
        state.manualOpen = false;
        state.skipNextCloseReconnect = true;
        state.reconnectSuppressed = true;
      },
      noteSocketOpened: () => {
        state.manualClose = false;
        state.manualOpen = false;
        state.reconnectSuppressed = false;
        state.terminalError = null;
      },
      noteUserCloseRequested: () => {
        state.manualClose = true;
        state.manualOpen = false;
        state.reconnectSuppressed = true;
        state.terminalError = null;
      },
      noteUserOpenRequested: () => {
        state.manualClose = false;
        state.manualOpen = true;
        state.reconnectSuppressed = false;
        state.terminalError = null;
      },
      noteUserReconnectClosed: () => {
        state.reconnectSuppressed = false;
      },
      noteUserReconnectRequested: () => {
        state.manualClose = false;
        state.manualOpen = true;
        state.skipNextCloseReconnect = true;
        state.reconnectSuppressed = true;
        state.terminalError = null;
      },
      peekTerminalError: () => state.terminalError
    };
  }

  return controllerRef.current;
};
